install:
  - choco install -y wget
  - wget -q https://download.microsoft.com/download/5/F/E/5FEB7E95-C643-48D5-8329-9D2C63676CE8/dotnet-dev-win-x64.1.0.0-rc4-004771.exe
  - dotnet-dev-win-x64.1.0.0-rc4-004771.exe /install /quiet /log dotnetinstall.log
  - ps: Push-AppveyorArtifact "dotnetinstall.log"

before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

on_success:
  - cmd: dotnet pack -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%
  - ps: Push-AppveyorArtifact "RemoteViewing\bin\Release\Quamotion.RemoteViewing.1.0.8-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"
  - ps: Push-AppveyorArtifact "RemoteViewing.Windows.Forms\bin\Release\Quamotion.RemoteViewing.Windows.Forms.1.0.8-r$($env:APPVEYOR_BUILD_NUMBER).nupkg"